name: at_demo_data
description: A library of data that contains demo enviroment variables and
  @sign credentials that can used for demo apps and testing
homepage: https://www.atsign.dev
documentation: https://atsign.dev/DocsPage
repository: https://github.com/atsign-company/at_demos

version: 0.9.0

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_cov: ^0.2.1
