name: iot_reciever
version: 1.0.3+11
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

#dependency_overrides:
#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: quickFixAtLookupRaceCondition
#
dependencies:
  cupertino_icons: ^1.0.2
  at_client_mobile: ^3.0.3
  at_onboarding_flutter: ^3.0.1
  at_utils: ^3.0.0
  path_provider: ^2.0.5
  flutter_dotenv: ^5.0.2
  at_app_flutter: any
  pretty_gauge: ^1.0.1
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  flutter: 
    sdk: flutter
  gradient_app_bar: ^0.1.3
  new_gradient_app_bar: ^0.2.0
dev_dependencies: 
  flutter_lints: ^1.0.0
  at_app_templates: ^1.0.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"

flutter: 
  assets: 
    - .env
    - assets/images/
  uses-material-design: true

