name: at_demo_data
description: A Dart library that contains testable atSign credentials and demo variables which can be used for testing with the local test environment.
homepage: https://www.atsign.dev
documentation: https://atsign.dev/docs/
repository: https://github.com/atsign-foundation/at_demos

version: 1.0.4

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
dev_dependencies:
  test: ^1.17.10
  test_cov: ^1.0.1
