name: at_chat_flutter_example
description: Welcome to our SB Hacks workshop session! This app demonstrates how
  to use the at_chat_flutter plugin.
version: 0.0.1
homepage: https://atsign.com/

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_chat_flutter: ^2.0.1
  at_demo_data: ^0.0.3+1
  at_onboarding_flutter: ^2.1.2
  at_server_status: ^1.0.1
  cupertino_icons: ^1.0.3
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
