name: newserverdemo
description: A new Flutter application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  at_client_mobile: ^2.0.4
  at_demo_data: ^1.0.0
  at_onboarding_flutter: ^2.1.3
  at_server_status: ^1.0.2
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
