name: static_analysis
# Runs the workflow on the below events:
# 1. on pull request raised to trunk branch.
# 2. on push event to trunk branch.
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30 # v1.6.4
        with:
          sdk: stable
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 'stable'
          cache-dependency-path: tools/osv-scanner/go.sum

      # Runs dart lint rules
      - name: Install dependencies and run analyze - mwc_demo/dart/iot_sender
        working-directory: ./mwc_demo/dart/iot_sender/
        run: |
          dart pub get
          dart analyze

      - name: Install dependencies and run analyze - at_notifications
        working-directory: ./at_notifications/
        run: |
          dart pub get
          dart analyze

      - name: Install dependencies and run analyze - at_demo_data
        working-directory: ./at_demo_data/
        run: |
          dart pub get
          dart analyze

      - name: Install dependencies and run analyze - at_data_share
        working-directory: ./at_data_share/
        run: |
          dart pub get
          dart analyze

      # Runs osv-scanner to find any vulnerable Dart dependencies
      # It needs to look at pubspec.lock files, which is why it's
      # placed here, as the `dart pub get` above will create them
      - name: Run osv-scanner
        run: |
          go install github.com/google/osv-scanner/cmd/osv-scanner@6316373e47d7e3e4b4fd3630c4bbc10987738de6 # v1.4.3
          osv-scanner --lockfile=./mwc_demo/dart/iot_sender/pubspec.lock
          osv-scanner --lockfile=./at_notifications/pubspec.lock
          osv-scanner --lockfile=./at_demo_data/pubspec.lock
          osv-scanner --lockfile=./at_data_share/pubspec.lock